package models;
// Generated 31 oct. 2018 14:57:30 by Hibernate Tools 5.3.6.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Adress generated by hbm2java
 */
public class Adress implements java.io.Serializable {

	private int id;
	private String city;
	private String street;
	private Set utilisateurs = new HashSet(0);

	public Adress() {
	}

	public Adress(int id) {
		this.id = id;
	}

	public Adress(int id, String city, String street, Set utilisateurs) {
		this.id = id;
		this.city = city;
		this.street = street;
		this.utilisateurs = utilisateurs;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getStreet() {
		return this.street;
	}

	public void setStreet(String street) {
		this.street = street;
	}

	public Set getUtilisateurs() {
		return this.utilisateurs;
	}

	public void setUtilisateurs(Set utilisateurs) {
		this.utilisateurs = utilisateurs;
	}

}
