package models;
// Generated 31 oct. 2018 14:57:30 by Hibernate Tools 5.3.6.Final

/**
 * Conversion generated by hbm2java
 */
public class Conversion implements java.io.Serializable {

	private int id;
	private byte[] date;
	private Double valueeuro;

	public Conversion() {
	}

	public Conversion(int id) {
		this.id = id;
	}

	public Conversion(int id, byte[] date, Double valueeuro) {
		this.id = id;
		this.date = date;
		this.valueeuro = valueeuro;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public byte[] getDate() {
		return this.date;
	}

	public void setDate(byte[] date) {
		this.date = date;
	}

	public Double getValueeuro() {
		return this.valueeuro;
	}

	public void setValueeuro(Double valueeuro) {
		this.valueeuro = valueeuro;
	}

}
