package models;
// Generated 31 oct. 2018 14:57:30 by Hibernate Tools 5.3.6.Final

/**
 * HibernateSequence generated by hbm2java
 */
public class HibernateSequence implements java.io.Serializable {

	private Long nextVal;

	public HibernateSequence() {
	}

	public HibernateSequence(Long nextVal) {
		this.nextVal = nextVal;
	}

	public Long getNextVal() {
		return this.nextVal;
	}

	public void setNextVal(Long nextVal) {
		this.nextVal = nextVal;
	}

}
