package models;
// Generated 31 oct. 2018 15:32:11 by Hibernate Tools 5.3.6.Final

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {
	private Integer idUser;
	private String login;
	private String nom;
	private String password;
	private String prenom;
	private String email;
	private boolean profil;

	public String toString() {
		String message = "user n°" + idUser + ", " + prenom + " " + nom + ", " + login + " " + email + " " + password
				+ ", ";
		if (profil)
			message += "in list";
		else
			message += "not in list";
		return message;
	}

	public User() {
	}

	public User(String email, boolean profil) {
		this.email = email;
		this.profil = profil;
	}

	public User(String login, String nom, String password, String prenom, String email, boolean profil) {
		this.login = login;
		this.nom = nom;
		this.password = password;
		this.prenom = prenom;
		this.email = email;
		this.profil = profil;
	}

	public Integer getIdUser() {
		return this.idUser;
	}

	public void setIdUser(Integer idUser) {
		this.idUser = idUser;
	}

	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public boolean isProfil() {
		return this.profil;
	}

	public void setProfil(boolean profil) {
		this.profil = profil;
	}

}
