package models;
// Generated 31 oct. 2018 14:57:30 by Hibernate Tools 5.3.6.Final

import java.util.Date;

/**
 * Utilisateur generated by hbm2java
 */
public class Utilisateur implements java.io.Serializable {

	private int id;
	private Adress adress;
	private String mdp;
	private Date naissance;
	private String prenom;

	public Utilisateur() {
	}

	public Utilisateur(int id) {
		this.id = id;
	}

	public Utilisateur(int id, Adress adress, String mdp, Date naissance, String prenom) {
		this.id = id;
		this.adress = adress;
		this.mdp = mdp;
		this.naissance = naissance;
		this.prenom = prenom;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Adress getAdress() {
		return this.adress;
	}

	public void setAdress(Adress adress) {
		this.adress = adress;
	}

	public String getMdp() {
		return this.mdp;
	}

	public void setMdp(String mdp) {
		this.mdp = mdp;
	}

	public Date getNaissance() {
		return this.naissance;
	}

	public void setNaissance(Date naissance) {
		this.naissance = naissance;
	}

	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

}
